name: balzanewsweb
description: "개발자 신문은 최신 개발 동향을 가장 빠르게 전달해드립니다."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  pointer_interceptor: ^0.10.1+2
  http: ^1.3.0
  go_router: 15.1.1
  idb_shim: 2.6.1+7
  firebase_messaging: ^15.2.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Noto Sans KR
      fonts:
        - asset: assets/fonts/KOHINanumOTF_Light.otf
    - family: Noto Emoji
      fonts:
        - asset: assets/fonts/Noto Emoji.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/KOHINanumOTF_Bold.otf

